env:
  es6: true
  node: true
  browser: true
  commonjs: true

extends: ['eslint:recommended', 'plugin:react/recommended']

globals:
  __INJECTED_CONFIG: true

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

parser: babel-eslint

rules:
  indent: [2, 2, {'SwitchCase': 1}]
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always

settings:
  react:
    version: latest
